FUNCTION(build_shaders)
	FILE(GLOB SHADERS_FILE_INPUTS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *.input)
	FOREACH(SHADERS_FILE_INPUT ${SHADERS_FILE_INPUTS})
		STRING(REGEX REPLACE "(.+)......" "\\1" fix-output ${SHADERS_FILE_INPUT})
		ADD_CUSTOM_COMMAND (
		  OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/temp/${fix-output}
		  COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/temp
		  COMMAND python ${VKDF_FIX_GLSL_PY} ${SHADERS_FILE_INPUT} ${CMAKE_CURRENT_BINARY_DIR}/temp/${fix-output}
		  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
		  COMMENT "GENERATING ${fix-output} from ${SHADERS_FILE_INPUT}"
		  DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${SHADERS_FILE_INPUT}
		  #VERBATIM
		)
		SET(FIX_OUTPUTS ${FIX_OUTPUTS} ${CMAKE_CURRENT_BINARY_DIR}/temp/${fix-output})
	ENDFOREACH()
	#ADD_CUSTOM_TARGET("${EXAMPLE_NAME}_Fixup-glsl" ALL DEPENDS ${FIX_OUTPUTS})

	#compile generated shader
	#SET(SHADER_FILES ${CMAKE_CURRENT_BINARY_DIR}/temp/*.frag ${CMAKE_CURRENT_BINARY_DIR}/temp/*.vert ${CMAKE_CURRENT_BINARY_DIR}/temp/*.geom  ${CMAKE_CURRENT_BINARY_DIR}/temp/*.comp)
	#FILE(GLOB SHADERS RELATIVE ${CMAKE_CURRENT_BINARY_DIR}/temp ${SHADER_FILES})

	FOREACH(GENERATED_SHADER_SOURCE ${FIX_OUTPUTS})
		get_filename_component(SHADER ${GENERATED_SHADER_SOURCE} NAME)
		SET(shader-output "${CMAKE_CURRENT_BINARY_DIR}/${SHADER}.spv")
		ADD_CUSTOM_COMMAND (
		  OUTPUT ${shader-output}
		  COMMAND ${GLSLC} ${GENERATED_SHADER_SOURCE} -o ${shader-output}
		  COMMENT "Compiling GENERATED ${GENERATED_SHADER_SOURCE}"
		  DEPENDS ${GENERATED_SHADER_SOURCE}
		  VERBATIM
		)
		SET(GEN_SHADER_OUTPUTS ${GEN_SHADER_OUTPUTS} ${shader-output})
	ENDFOREACH()
	#ADD_CUSTOM_TARGET("${EXAMPLE_NAME}_BuildGeneratedShaders" ALL DEPENDS ${GEN_SHADER_OUTPUTS})
	#add_dependencies ("${EXAMPLE_NAME}_BuildGeneratedShaders" "${EXAMPLE_NAME}_Fixup-glsl")

	#compile handmade shaders
	SET(SHADER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.frag ${CMAKE_CURRENT_SOURCE_DIR}/*.vert ${CMAKE_CURRENT_SOURCE_DIR}/*.geom  ${CMAKE_CURRENT_SOURCE_DIR}/*.comp)
	FILE(GLOB SHADERS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${SHADER_FILES})
	FOREACH(SHADER ${SHADERS})
		SET(shader-input ${CMAKE_CURRENT_SOURCE_DIR}/${SHADER})
		SET(shader-output ${CMAKE_CURRENT_BINARY_DIR}/${SHADER}.spv)
		ADD_CUSTOM_COMMAND (
		  OUTPUT ${shader-output}
		  COMMAND ${GLSLC} ${shader-input} -o ${shader-output}
		  COMMENT "Compiling ${shader-input}"
		  DEPENDS ${SHADER}
		  VERBATIM
		)
		SET(SHADER_OUTPUTS ${SHADER_OUTPUTS} ${shader-output})
	ENDFOREACH()

	#ADD_CUSTOM_TARGET("${EXAMPLE_NAME}_BuildShaders" ALL DEPENDS ${SHADER_OUTPUTS})

	SET(SHADER_OUTPUTS ${SHADER_OUTPUTS} PARENT_SCOPE)
	SET(GEN_SHADER_OUTPUTS ${GEN_SHADER_OUTPUTS} PARENT_SCOPE)
ENDFUNCTION()
